name: build

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - image-server

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Output lowercase repository name
        id: lowercase_repository
        run: echo "LOWERCASE_REPOSITORY=$(echo ${{ github.repository }} | awk '{ print tolower($0) }')" >> $GITHUB_OUTPUT
      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          push: true
          target: ${{ matrix.target }}
          tags: ghcr.io/${{ steps.lowercase_repository.outputs.LOWERCASE_REPOSITORY }}/${{ matrix.target }}:latest
          cache-from: type=gha,scope=build-${{ matrix.target }}
          cache-to: type=gha,mode=max,scope=build-${{ matrix.target }}
